/**/// DO NOT MODIFY THIS FILE MANUALLY
/**/// This class was automatically generated by "GeneratePatternClasses.java",
/**/// modify the "unique_patterns.json" and re-generate instead.

package ac.mdiq.vista.extractor.timeago.patterns;

import ac.mdiq.vista.extractor.timeago.PatternsHolder;

public class ms extends PatternsHolder {
    private static final String WORD_SEPARATOR = " ";
    private static final String[]
            SECONDS  /**/ = {"saat"},
            MINUTES  /**/ = {"minit"},
            HOURS    /**/ = {"jam"},
            DAYS     /**/ = {"hari"},
            WEEKS    /**/ = {"minggu"},
            MONTHS   /**/ = {"bulan"},
            YEARS    /**/ = {"tahun"};

    private static final ms INSTANCE = new ms();

    public static ms getInstance() {
        return INSTANCE;
    }

    private ms() {
        super(WORD_SEPARATOR, SECONDS, MINUTES, HOURS, DAYS, WEEKS, MONTHS, YEARS);
    }
}
